remote_theme: just-the-docs/just-the-docs
logo: "/assets/Icon.png"
aux_links:
  "Github Repository":
    - "//github.com/AnnikenYT/sdui-sdk-js"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/annikenyt/sdui-sdk-js" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

color_scheme: dark