name: Publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/AnnikenYT
      - run: npm install
      - run: npm run test
        env:
          SDUI_TOKEN: ${{ secrets.SDUI_TOKEN }}
          SDUI_USER_ID: ${{ secrets.SDUI_USER_ID }}
          SDUI_EMAIL: ${{ secrets.SDUI_EMAIL }}
          SDUI_PASSWORD: ${{ secrets.SDUI_PASSWORD }}
          SDUI_SCHOOL: ${{ secrets.SDUI_SCHOOL }}
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PACKAGES_TOKEN }}